de-duplicate genes, collapse file/type
federicomarini/annoFuseData pull request #12
Opened 2024-08-01 22:20 UTC by jharenza

Using the below code, deduplicated the genes

```r
genelist <- "annoFuseData/inst/extdata/genelistreference.txt"
dupgenes <- genelist[duplicated(genelist$Gene_Symbol),"Gene_Symbol"]

genelist_dedup <- genelist %>%
  group_by(Gene_Symbol, classification) %>%
  mutate(file = case_when(is.na(classification) ~ gsub(", OncoKBv20240704", "", file), 
                          TRUE ~ file)) %>%
  reframe(type = paste(unique(trimws(unlist(strsplit(type, ", ")))), collapse = ", "),
          file = paste(unique(trimws(unlist(strsplit(file, ", ")))), collapse = ", ")) %>%
  select(-classification) %>%
  write_tsv("~/Documents/GitHub/annoFuseData/inst/extdata/genelistreference.txt")

> length(dupgenes$Gene_Symbol) == nrow(genelist)-nrow(genelist_dedup)
[1] TRUE

```

2024-08-01 22:21 UTC, jharenza commented on inst/extdata/genelistreference.txt
> -CDK1	Kinase	PfamKinase, OncoKBv20240704	NA
EXAMPLE

2024-08-02 13:31 UTC, rjcorb requested changes
It looks like the deduplication code that is in the PR description is not included in `annoFuseData_update.R`. When I run the script using the `master` branch version of `genelistreference.txt` as input, I still get duplicated gene rows: 

```
  Gene_Symbol type   file                                  
  <chr>       <chr>  <chr>                                 
1 CDK1        Kinase Kincat_Hsap.08.02.txt, OncoKBv20240704
2 CDK1        Kinase PfamKinase, OncoKBv20240704    
```

2024-08-02 13:38 UTC, jharenza commented
> ```r
> %>%
>   group_by(Gene_Symbol, classification) %>%
>   mutate(file = case_when(is.na(classification) ~ gsub(", OncoKBv20240704", "", file), 
>                           TRUE ~ file)) %>%
>   reframe(type = paste(unique(trimws(unlist(strsplit(type, ", ")))), collapse = ", "),
>           file = paste(unique(trimws(unlist(strsplit(file, ", ")))), collapse = ", ")) %>%
>   select(-classification) %>%
> ```

true, i did not add it there - tbh, this is tough because the preprocessing code was never a part of this package and technically this should not be an issue going forward. However, I have just added it in case it is- can you retest?

2024-08-02 15:00 UTC, rjcorb approved these changes
ok everything looks good now

2024-08-02 15:02 UTC, merged